workflows:
  vmx-workflow:
    name: VMX Pipeline
    scripts:
      - name: CICD Started
        script: echo "Welcome to CICD set up"
    publishing:
      email:
        recipients:
          - monishapvadivelu@outlook.com
