# Generated by Django 4.1.6 on 2023-03-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleScanAPI', '0002_schedulescan_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescan',
            name='patientID',
            field=models.IntegerField(default=0),
        ),
    ]
