# Generated by Django 4.1.6 on 2023-03-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleScanAPI', '0003_alter_schedulescan_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulescan',
            name='patientID',
            field=models.CharField(max_length=50),
        ),
    ]
