# Generated by Django 4.1.6 on 2023-03-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleScanAPI', '0004_alter_schedulescan_patientid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulescan',
            name='patientID',
        ),
    ]
