# Generated by Django 4.1.6 on 2023-03-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleScanAPI', '0005_remove_schedulescan_patientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulescan',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
