# Generated by Django 4.1.3 on 2022-11-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('dob', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('medcondition', models.CharField(max_length=300)),
                ('patientdescription', models.CharField(max_length=600)),
                ('symptoms', models.CharField(max_length=500)),
                ('medication', models.CharField(max_length=500)),
                ('notes', models.CharField(max_length=600)),
            ],
        ),
    ]
