# Generated by Django 4.1.3 on 2023-04-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nhsNo',
            field=models.CharField(default='P000000', max_length=50),
        ),
    ]
