# Generated by Django 4.1.3 on 2023-04-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_nhsno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nhsNo',
        ),
    ]
