# Generated by Django 4.1.3 on 2023-04-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_nhsno'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nhsNo',
            field=models.CharField(default='P00000', max_length=50),
        ),
    ]
